### ISSUE TITLE
Yahoo link does not work when using allDay: true

### ISSUE THREAD

**Issue by willenium** [jojoee/add2calendar#12]
When wanting to show an event with a duration of all day, we need to set the `dur` value in the Yahoo link to `allday`.
I see in the code that this is commented out. But without it, it does not work.
For this to work the endDate has to be the startDate + 1 day.

Great plugin btw :)

**Comment by jojoee** [comment]
Hi @willenium 
Thank you so much kub, for the contribution to both reporting and solution 😄 .
I manage to fix and release in v1.1.8
