### ISSUE TITLE
Allow specifying text for button

### ISSUE THREAD

**Issue by cheapsteak** [jojoee/add2calendar#2]
Instead of (or in addition to) `add2calendarBtnTextMap`, be able to pass in the text to display as part of the options in the constructor, what do you think?

**Comment by jojoee** [comment]
Agree, will do.

**Comment by jojoee** [comment]
Done - I've refactor option system a bit, you can see the changes on [this commit](https://github.com/jojoee/add2calendar/commit/b7c15f14b02e9ea9bf03bca040fdfb6977cfe303)
