### ISSUE TITLE
Event is truncated when title contains a "#" character

### ISSUE THREAD

**Issue by dougauerbach** [jojoee/add2calendar#4]
When the title contains a hash character (#) the iCal version of the event is truncated.

See codepen: 
https://codepen.io/anon/pen/NooReL?editors=1111

**Comment by jojoee** [comment]
@dougauerbach sorry for the late reply, I haven't check this repo for a while.
But indeed, I fix it, so now it is not truncated when contains # character.
https://github.com/jojoee/add2calendar/commit/9732913c3cd4d40bef8a00a7db65ebbc0a69d9e7
