### ISSUE TITLE
All-day events

### ISSUE THREAD

**Issue by HGZdev** [jojoee/add2calendar#8]
Hello, 

I would like to ask if there is any possible way to add new event to google calendar with `all day event` checkbox checked? Could you provide me an example of such event implementation in `add2calendar`? 

Ideally this kind of code...
```
var singleEventArgs = {
  title       : 'Add2Calendar plugin event',
  start       : 'July 27, 2016 10:30',
  end         : 'July 29, 2016 19:20',
  location    : 'Bangkok, Thailand',
  description : 'Event description' 
  allDay: true,
};
```
... would be displayed in Google Calendar as:
```
startDate: July 27, 2016 
endDate: July 29, 2016
allDay: 'ticked'
(...)
```

**Comment by jojoee** [comment]
Hi @HGZdev, hmm very interesting.
I'm currently not sure if it possible, let me dig into it.

**Comment by HGZdev** [comment]
I think it would be very useful to have such an option. Otherwise we receive at best something like this :
```
  start       : 'July 27, 2016 00:00',
  end         : 'July 29, 2016 23:59',
```

**Comment by HGZdev** [comment]
Hello @jojoee , any news on this issue?

**Comment by jojoee** [comment]
He @HGZdev, I just updated it and deployed it with version 1.1.4.
Seems to be worked on Google and iCal but no chance for yahoo.

**Comment by HGZdev** [comment]
It seems to work fine now. Thanks!
